product=input("Product bought:")
quantity=input("How much do you need:")
price=input("Enter the price:")
bill=int(quantity)*float(price)
print()
print("----------------------")
print("Your Invoice:")
print("----------------------")
print(" - Product:",product)
print(" - Quantity:",quantity)
print(" - Price:",price)
print("Total to Pay: $",bill)